const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||(fs.existsSync(path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))?path.join(require('os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'):'playwright'));
const PORT=Number(process.env.PORT||8798);
const root=path.resolve(process.env.GAME_ROOT||path.join(__dirname,'../../www')),out=path.resolve(process.env.QA_OUT||path.join(__dirname,'results'));fs.mkdirSync(out,{recursive:true});
const html=fs.readFileSync(root+'/index.html','utf8');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);for(const f of ['art-v2.js','world-ab.js'])new vm.Script(fs.readFileSync(root+'/'+f,'utf8'));
const server=http.createServer((req,res)=>{const file=path.join(root,decodeURIComponent(req.url.split('?')[0]==='/'?'index.html':req.url.split('?')[0]));if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.png')?'image/png':file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':file.endsWith('.ttf')?'font/ttf':'text/html;charset=utf-8');res.end(file.endsWith('index.html')?fs.readFileSync(file,'utf8').replace('// Android back handling','window.__testEval=function(code){return eval(code);};\n// Android back handling'):fs.readFileSync(file));});
async function launch(){await new Promise(r=>server.listen(PORT,'127.0.0.1',r));return chromium.launch({executablePath:process.env.EDGE_PATH||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding','--disable-backgrounding-occluded-windows']});}
const ev=(p,s)=>p.evaluate(s=>window.__testEval(s),s);
async function start(p,map='uskudar'){await p.goto(`http://127.0.0.1:${PORT}`);await p.locator('.mb-play').click();await p.locator('.ccard').filter({hasText:'USTURA'}).click();await p.locator('#charScreen .bok').click();const entry=await ev(p,`(()=>{const m=MAPS.find(m=>m.id===${JSON.stringify(map)});if(!m)throw Error('Unknown QA map');return {id:m.id,name:m.name,gated:!!m.comingSoon||!!(m.unlockLevel&&getAccountLevel()<m.unlockLevel)};})()`);if(entry.gated){if(process.env.QA_ALL_MAPS!=='1')throw Error('QA map needs QA_ALL_MAPS=1: '+map);await ev(p,`selMap=MAPS.find(m=>m.id===${JSON.stringify(map)})`);}else await p.locator('.mcard').filter({hasText:entry.name}).click();await p.locator('#mapScreen .bok').click();if(await p.locator('#storyBtn').isVisible())await p.locator('#storyBtn').click();let chosen=false;if(process.env.QA_MODIFIERS==='1'){for(const name of ['AURA MODU','MİNİ OYUNCU','BERSEKİR','HIZ ZAMANI','SÜPER MANYETO','KALKAN BAŞLAT','KESKİN NİŞANCI']){let option=p.locator('[data-mi]').filter({hasText:name});if(await option.count()){await option.first().click();chosen=true;break;}}}if(!chosen)await p.locator('[data-mi="-1"]').click();return {map:entry.id,entry:entry.gated?'QA-only gated map selection; gameplay unchanged':'UI map selection'};}
module.exports={fs,path,out,root,server,launch,ev,start};
if(require.main===module)(async()=>{const b=await launch(),errors=[];try{const p=await b.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.stack));await p.goto(`http://127.0.0.1:${PORT}`);let layouts=[];for(const [width,height] of [[390,844],[540,1310],[844,390],[932,430]]){await p.setViewportSize({width,height});await p.waitForTimeout(300);layouts.push(await p.evaluate(()=>({vp:[innerWidth,innerHeight],app:document.querySelector('#app').getBoundingClientRect().toJSON(),logo:document.querySelector('.mt2').getBoundingClientRect().toJSON(),title:document.querySelector('.mtitle-wrap').getBoundingClientRect().toJSON(),play:document.querySelector('.mb-play').getBoundingClientRect().toJSON()})));await p.screenshot({path:out+'/menu-'+width+'x'+height+'.png'});}await p.setViewportSize({width:390,height:844});await start(p);await p.waitForTimeout(1500);console.log(await ev(p,'({P,elapsed,world:worldObj.objects.length,modal:modalOpen()})'));fs.writeFileSync(out+'/smoke.json',JSON.stringify({errors,layouts},null,2));await p.screenshot({path:out+'/smoke-game.png'});console.log({errors,layouts});}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
