const {fs,out,root,server,launch,ev,start}=require('./ab-harness.cjs');
(async()=>{const b=await launch();try{const results=[];for(const [map,runCount] of Object.entries(JSON.parse(process.env.QA_RUNS||'{"uskudar":5,"besiktas":5}'))){await Promise.all(Array.from({length:runCount},async(_,i)=>{const ctx=await b.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));let result={map,run:i+1,freshStorage:true,method:'Real requestAnimationFrame + UI clicks + Playwright keyboard, no state mutations or cheats',samples:[],errors},held=[],previous={x:1,y:0};await start(p,map);result.version=await p.evaluate(()=>APP_VERSION);result.sourceHash=require('crypto').createHash('sha256').update(fs.readFileSync(root+'/index.html')).digest('hex');const began=Date.now();const spawn=await ev(p,'({x:P.x,y:P.y,free:WorldRules.free(worldObj,P.x,P.y,P.r)})');await p.waitForTimeout(120);const after=await ev(p,'({x:P.x,y:P.y})');result.spawn=spawn;result.idleSpawnDisplacement=Math.hypot(after.x-spawn.x,after.y-spawn.y);let lastLog=-1;
while(Date.now()-began<600000){
 if(await p.locator('#tutBtn').isVisible()){await p.locator('#tutBtn').click({timeout:1000}).catch(()=>{});}
 if(await p.locator('#lvlup.on .luc').count()){await p.locator('#lvlup.on .luc').first().click({timeout:1000}).catch(()=>{});}
 if(await p.locator('#bossChestOverlay').isVisible()){let btn=p.locator('#bossChestOverlay button');if(await btn.count())await btn.first().click({timeout:1000}).catch(()=>{});}
 let s=await ev(p,`(()=>{const dirs=[[1,0],[-1,0],[0,1],[0,-1],[.707,.707],[.707,-.707],[-.707,.707],[-.707,-.707]];return {elapsed,end:_runEnded,hp:P.hp,god:!!P._godMode,paused,modal:modalOpen(),x:P.x,y:P.y,level:P.lvl,kills,modifier:pdata.runModifier,ultReady:CHAR_ULTS[P.char.id].t>=CHAR_ULTS[P.char.id].cd,enemies:enemies.length,free:WorldRules.free(worldObj,P.x,P.y,P.r),near:Math.min(...enemies.map(e=>Math.hypot(P.x-e.x,P.y-e.y)-e.r)),choices:dirs.map(([x,y])=>{let clear=[12,24,40].every(d=>WorldRules.free(worldObj,P.x+x*d,P.y+y*d,P.r+2));let score=0;enemies.forEach(e=>{let d=Math.max(8,Math.hypot(P.x+x*100-e.x,P.y+y*100-e.y)-e.r);score-=20000/(d*d);});let nearOrb=orbs.reduce((m,o)=>Math.min(m,Math.hypot(P.x+x*100-o.x,P.y+y*100-o.y)),1000);score-=nearOrb*.0015;if(P.hp<P.mhp*.65&&healthOrbs.length){let d=Math.min(...healthOrbs.map(o=>Math.hypot(P.x+x*100-o.x,P.y+y*100-o.y)));score-=Math.min(700,d)*.01;}return {x,y,score:score+(clear?0:-10000)}})};})()`);
 if(!s.free)result.collisionViolations=(result.collisionViolations||0)+1;if(lastLog!==Math.floor(s.elapsed/10000)){lastLog=Math.floor(s.elapsed/10000);result.samples.push({...s,choices:undefined});fs.writeFileSync(out+'/natural-'+map+'-'+(i+1)+'.json',JSON.stringify(result,null,2));}
 if(s.end||s.elapsed>=180000){result.final={...s,choices:undefined};break;}
 const best=s.choices.sort((a,z)=>(z.score+(z.x*previous.x+z.y*previous.y)*.08)-(a.score+(a.x*previous.x+a.y*previous.y)*.08))[0];previous=best;let desired=s.modal||s.paused?[]:[...(best.x>.1?['d']:best.x<-.1?['a']:[]),...(best.y>.1?['s']:best.y<-.1?['w']:[])];for(const k of held)if(!desired.includes(k))await p.keyboard.up(k);for(const k of desired)await p.keyboard.down(k);held=desired;if(s.near<100&&!s.modal)await p.keyboard.press('Shift');if(s.ultReady&&s.near<200&&!s.modal)await p.locator('#ultHud').click({timeout:1000}).catch(()=>{});await p.waitForTimeout(180);
 }
 for(const k of held)await p.keyboard.up(k);result.wallSeconds=(Date.now()-began)/1000;result.pass=!!result.final&&result.final.elapsed>=180000&&!result.final.god&&result.idleSpawnDisplacement===0&&errors.length===0&&!result.collisionViolations&&result.samples.every(x=>x.free);await p.screenshot({path:out+'/natural-'+map+'-'+(i+1)+'.png'});fs.writeFileSync(out+'/natural-'+map+'-'+(i+1)+'.json',JSON.stringify(result,null,2));results.push(result);console.log(JSON.stringify({map,run:i+1,pass:result.pass,final:result.final,wallSeconds:result.wallSeconds,errors}));await ctx.close();}));}fs.writeFileSync(out+'/natural-summary.json',JSON.stringify(results,null,2));}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
