const {fs,out,root,server,launch,ev,start}=require('./ab-harness.cjs');
const {chooseUpgrade}=require('./ab-ui.cjs');
const naturalMs=Number(process.env.QA_NATURAL_SECONDS||180)*1000;
const maxWallMs=Math.max(600000,naturalMs*3+60000);
(async()=>{const b=await launch();try{const results=[];for(const [map,runCount] of Object.entries(JSON.parse(process.env.QA_RUNS||'{"uskudar":5,"besiktas":5}'))){await Promise.all(Array.from({length:runCount},async(_,i)=>{const ctx=await b.newContext({viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));let result={map,run:i+1,freshStorage:true,method:'Real requestAnimationFrame + UI clicks + Playwright keyboard, no state mutations or cheats',samples:[],errors,failures:[],death:false},held=[],previous={x:1,y:0};const watchdog=setTimeout(()=>{errors.push('renderer/run watchdog timeout');ctx.close().catch(()=>{});},maxWallMs+30000);watchdog.unref();result.setup=await start(p,map);const actualMap=await ev(p,'selMap.id');if(actualMap!==map)throw Error('Wrong map: '+actualMap+' requested '+map);result.version=await p.evaluate(()=>APP_VERSION);result.sourceHash=require('crypto').createHash('sha256').update(fs.readFileSync(root+'/index.html')).digest('hex');if(process.env.QA_DAMAGE_TRACE==='1')result.initialThreats=await ev(p,'({wave,level:P.lvl,x:P.x,y:P.y,free:WorldRules.free(worldObj,P.x,P.y,P.r),enemies:enemies.map(e=>({id:e.type.id,distance:dn(P,e),hp:e.hp,speed:e.spd,damage:e.dmg}))})');const began=Date.now();const spawn=await ev(p,'({x:P.x,y:P.y,free:WorldRules.free(worldObj,P.x,P.y,P.r)})');await p.waitForTimeout(120);const after=await ev(p,'({x:P.x,y:P.y})');result.spawn=spawn;result.idleSpawnDisplacement=Math.hypot(after.x-spawn.x,after.y-spawn.y);let lastLog=-1,lastElapsed=-1,lastProgressAt=Date.now();
const targetMs=Math.min(naturalMs,Number(await ev(p,'selMap.speedrun?(selMap.speedrunTime||180)*1000:0'))||naturalMs);result.targetSeconds=targetMs/1000;
while(Date.now()-began<maxWallMs){
 let handledModal=false;
 if(await p.locator('#tutBtn').isVisible()){await p.locator('#tutBtn').click({timeout:1000});handledModal=true;}
 if(await p.locator('#lvlup.on .luc').count()){handledModal=(await chooseUpgrade(p))||handledModal;}
 if(await p.locator('#bossChestOverlay').isVisible()){let btn=p.locator('#bossChestOverlay button');if(await btn.count()){await btn.first().click({timeout:1000});handledModal=true;}}
 // Production resets keys on modal entry. Re-press the desired direction afterwards.
 if(handledModal){for(const k of held)await p.keyboard.up(k);held=[];}
 let s=await ev(p,`(()=>{const dirs=[[1,0],[-1,0],[0,1],[0,-1],[.707,.707],[.707,-.707],[-.707,.707],[-.707,-.707]];return {elapsed,end:_runEnded,hp:P.hp,god:!!P._godMode,paused,modal:modalOpen(),x:P.x,y:P.y,level:P.lvl,kills,modifier:pdata.runModifier,ultReady:CHAR_ULTS[P.char.id].t>=CHAR_ULTS[P.char.id].cd,enemies:enemies.length,free:WorldRules.free(worldObj,P.x,P.y,P.r),near:Math.min(...enemies.map(e=>Math.hypot(P.x-e.x,P.y-e.y)-e.r)),choices:dirs.map(([x,y])=>{let clear=[12,24,40].every(d=>WorldRules.free(worldObj,P.x+x*d,P.y+y*d,P.r+2));let score=0;enemies.forEach(e=>{let d=Math.max(8,Math.hypot(P.x+x*100-e.x,P.y+y*100-e.y)-e.r);score-=20000/(d*d);});let nearOrb=orbs.reduce((m,o)=>Math.min(m,Math.hypot(P.x+x*100-o.x,P.y+y*100-o.y)),1000);score-=nearOrb*.0015;if(P.hp<P.mhp*.65&&healthOrbs.length){let d=Math.min(...healthOrbs.map(o=>Math.hypot(P.x+x*100-o.x,P.y+y*100-o.y)));score-=Math.min(700,d)*.01;}return {x,y,score:score+(clear?0:-10000)}})};})()`);
 if(!s.free)result.collisionViolations=(result.collisionViolations||0)+1;if(s.elapsed!==lastElapsed){lastElapsed=s.elapsed;lastProgressAt=Date.now();}else if(Date.now()-lastProgressAt>=15000){result.failures.push('stalled: game clock unchanged for 15 seconds');}if(lastLog!==Math.floor(s.elapsed/10000)){lastLog=Math.floor(s.elapsed/10000);result.samples.push({...s,choices:undefined});fs.writeFileSync(out+'/natural-'+map+'-'+(i+1)+'.json',JSON.stringify(result,null,2));}
 if(s.end||s.elapsed>=targetMs||errors.length||result.collisionViolations||result.failures.length){result.final={...s,choices:undefined};break;}
 const best=s.choices.sort((a,z)=>(z.score+(z.x*previous.x+z.y*previous.y)*.08)-(a.score+(a.x*previous.x+a.y*previous.y)*.08))[0];previous=best;let desired=s.modal||s.paused?[]:[...(best.x>.1?['d']:best.x<-.1?['a']:[]),...(best.y>.1?['s']:best.y<-.1?['w']:[])];for(const k of held)if(!desired.includes(k))await p.keyboard.up(k);for(const k of desired)await p.keyboard.down(k);held=desired;if(s.near<100&&!s.modal)await p.keyboard.press('Shift');if(s.ultReady&&s.near<200&&!s.modal)await p.locator('#ultHud').click({timeout:1000}).catch(()=>{});await p.waitForTimeout(180);
 }
 for(const k of held)await p.keyboard.up(k);result.wallSeconds=(Date.now()-began)/1000;result.death=!!result.final&&result.final.end&&result.final.hp<=0;result.completed=!!result.final&&result.final.elapsed>=targetMs;
 if(!result.final)result.failures.push('wall-timeout: run did not finish within '+(maxWallMs/1000)+' seconds');
 if(result.final&&!result.completed&&!result.death)result.failures.push('incomplete: ended before target duration without combat death');
 if(!result.spawn.free||result.collisionViolations||result.samples.some(x=>!x.free))result.failures.push('collision violation');
 if(result.idleSpawnDisplacement!==0)result.failures.push('uncommanded spawn displacement');
 if(errors.length)result.failures.push('JavaScript error');
 if(result.final?.god||result.samples.some(x=>x.god))result.failures.push('cheat enabled');
 if(process.env.QA_DAMAGE_TRACE==='1')result.damageTrace=await p.evaluate(()=>window.__deathTrace);result.pass=result.failures.length===0;result.outcome=result.pass?(result.death?'death':'completed'):'error';await p.screenshot({path:out+'/natural-'+map+'-'+(i+1)+'.png'});fs.writeFileSync(out+'/natural-'+map+'-'+(i+1)+'.json',JSON.stringify(result,null,2));results.push(result);console.log(JSON.stringify({map,run:i+1,pass:result.pass,death:result.death,outcome:result.outcome,failures:result.failures,final:result.final,wallSeconds:result.wallSeconds,errors}));clearTimeout(watchdog);await ctx.close();}));}fs.writeFileSync(out+'/natural-summary.json',JSON.stringify(results,null,2));if(results.some(result=>!result.pass))process.exitCode=1;}finally{await b.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
